// src/integrations/supabase/client.ts
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { createSupabaseBrowserConfig } from "@/config/supabase";
import type { Database } from "./types";

const supabaseConfig = createSupabaseBrowserConfig();

export const supabase = createClient<Database>(
  supabaseConfig.url,
  supabaseConfig.anonKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
  },
);
